input_file: Driver_survey.csv
columns:
  record_key: KEY
  instance_id: instanceID
  submission_date: SubmissionDate
  enumerator: Enumerator
  enumerator_id: Enumerator_id
  deviceid: deviceid
  starttime: starttime
  endtime: endtime
  duration: duration
  travel_time_min: starttime
  fee: feel_good
  driver_phone: devicephonenum
  school: school
  district: district
all_columns:
- SubmissionDate
- starttime
- endtime
- deviceid
- devicephonenum
- device_info
- duration
- audio
- text_audit
- Enumerator
- Enumerator_name
- Enumerator_id
- district
- school
- driver
- driver_name
- number
- understand
- copy
- agree
- demographics_presence
- demographics_presence_1
- demographics_presence_2
- name
- age
- phonenumber
- education
- smartphone
- community
- community_other
- marital_status
- more_than_one_wife
- marriage_duration1
- marriage_duration
- wife_age1
- wife_age
- children
- daughters
- sons
- daughters_roster_count
- daughters_roster_presence_1
- daughters_roster_presence_1_1
- daughters_roster_presence_2_1
- index_1
- daughers_age_1
- currently_studying_1
- education_level_1
- education_level1_1
- daughters_roster_presence_2
- daughters_roster_presence_1_2
- daughters_roster_presence_2_2
- index_2
- daughers_age_2
- currently_studying_2
- education_level_2
- education_level1_2
- daughters_roster_presence_3
- daughters_roster_presence_1_3
- daughters_roster_presence_2_3
- index_3
- daughers_age_3
- currently_studying_3
- education_level_3
- education_level1_3
- daughters_roster_presence_4
- daughters_roster_presence_1_4
- daughters_roster_presence_2_4
- index_4
- daughers_age_4
- currently_studying_4
- education_level_4
- education_level1_4
- daughters_roster_presence_5
- daughters_roster_presence_1_5
- daughters_roster_presence_2_5
- index_5
- daughers_age_5
- currently_studying_5
- education_level_5
- education_level1_5
- employment_presence
- employment_presence_1
- employment_presence_2
- employment_transport
- employment_duration
- schoolname
- who_hired
- other_hire
- hours_work
- days_work
- payment
- payment_delay
- secondary_work
- secondary_work1
- secondary_work1_1
- secondary_work1_2
- secondary_work1_3
- other_secondary_work
- payment_secondary_work
- beliefs_presence
- beliefs_presence_1
- beliefs_presence_2
- women_rights
- equality
- leaders
- scare_jobs
- provider
- work_for_pay
- work_after_marriage
- childcare
- speakout
- mistreatment
- stay_silent
- report_incident
- dress
- inappropriate_comments
- choice_clothes
- harassment
- girl_school
- secondary_school
- boys
- married
- childraising
- higher_edu
- secondordernorms_presence
- secondordernorms_presence_1
- secondordernorms_presence_2
- speakout1
- mistreatment1
- stay_silent1
- report_incident1
- dress1
- inappropriate_comments1
- choice_clothes1
- harassment1
- girl_school1
- secondary_school1
- boys1
- married1
- childraising1
- higher_edu1
- motives_for_violence_presence
- motives_for_violence_presence_1
- motives_for_violence_presence_2
- treat_badly
- talk_back
- feel_good
- no_consequences
- social_desireability_presence
- social_desireability_presence_1
- social_desireability_presence_2
- work
- resentful
- ability
- rebel
- good_listener
- took_advantage
- admit_mistake
- get_even
- courteous
- irked
- jealous
- favors
- hurt_feelings
- masculinity_presence
- masculinity_presence_1
- masculinity_presence_2
- never_depend
- shouldnt_cry
- worried_afraid
- feelings
- girl_mistreated_presence
- girl_mistreated_presence_1
- girl_mistreated_presence_2
- dress_norm_acceptable
- dress_norm_acceptable1
- action_improve
- dress_norm_action
- dress_norm_action_other
- dress_norm_action1
- overcrowding_acceptable
- overcrowing_acceptable1
- overcrowding_improve
- overcrowding_action
- overcrowding_action_other
- overcrowding_action1
- respect_acceptable
- respect_acceptable1
- respect_improve
- respect_action
- respect_action_other
- respect_action1
- gender_equality_edu_presence
- gender_equality_edu_presence_1
- gender_equality_edu_presence_2
- higher_education_acceptable
- higher_education_acceptable1
- higher_education_improve
- higher_education_action
- higher_education_action_other
- higher_education_action1
- exams_acceptable
- exams_acceptable1
- exams_improve
- exams_action
- exams_action_other
- exams_action1
- boys_edu_acceptable
- boys_edu_acceptable1
- boys_edu_improve
- boys_edu_action
- boys_edu_action_other
- boys_edu_action1
- instanceID
- formdef_version
- KEY
- review_status
- review_quality
- review_comments
- review_corrections
